-- Migration: gpx_info
-- Created at: 2023-10-17 15:14:51
-- ====  UP  ====

BEGIN;
  CREATE TABLE IF NOT EXISTS gpx_info (
    id serial PRIMARY KEY,
    user_file_id integer NOT NULL,
    duration_secs integer,
    distance_ft integer,
    gained_elevation_ft integer,
    lost_elevation_ft integer,

    CONSTRAINT fk_user_files FOREIGN KEY (user_file_id) REFERENCES user_files (id)
  );

  COMMENT ON TABLE gpx_info IS 'summary info on user uploaded gpx files, usually generated by the client';

COMMIT;

-- ==== DOWN ====

BEGIN;
  DROP TABLE gpx_info
COMMIT;
